language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t vgorozhanov/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true vgorozhanov/docker-react npm run test